image: jakzal/phpqa:php7.4

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - vendor/

before_script:
    - composer install #instal le composer avant le lancement du script et mis en cache du dossier vendor

#cache:
#    key: ${CI_COMMIT_REF_SLUG}
#    paths:
#        - vendor/

#les bundles que l'ont va utiliser su paquet pour nos tests suivant les étapes de tests
stages:
    - LocalPhpSecurityChecker
    - CodingStandards
    - UnitTests

#Run de phases de Tests
local-php-security-checker:
    stage: LocalPhpSecurityChecker
    script:
        - local-php-security-checker security:check composer.lock
    allow_failure: false

phpcs:
    stage: CodingStandards
    script:
        - phpcs -v --standard=PSR2 --ignore=./src/Kernel.php ./src
    allow_failure: false

phpstan:
    stage: CodingStandards
    script:
        - phpstan analyse ./src
    allow_failure: false

twig-lint:
    stage: CodingStandards
    script:
        - twig-lint lint ./templates
    allow_failure: false
# dernière étape des tests statiques
#phpunit:
#    stage: UnitTests
#    script:
#        - php bin/phpunit
#    allow_failure: false


#Mis en place des paramètres pour le testfonctionnel avec phpunit en introduisant la bdd
phpunit:
    image: php:7.4-apache
    stage: UnitTests
    services:
        - name: mysql:5.7
          alias: mysql
    variables:
        MYSQL_ROOT_PASSWORD: pass_test
        MYSQL_DATABASE: myapptest
        MYSQL_USER: myapptest
        MYSQL_PASSWORD: myapptest
        DATABASE_URL: 'mysql://myapptest:myapptest@mysql:3306/myapptest'
    before_script:
        - apt-get update && apt-get install -y git libzip-dev
        - curl -sSk https://getcomposer.org/installer | php -- --disable-tls && mv composer.phar /usr/local/bin/composer
        - docker-php-ext-install mysqli pdo pdo_mysql zip
        - php bin/console doctrine:database:drop --force --env=test
        - php bin/console doctrine:database:create --env=test
        - php bin/console doctrine:migration:migrate --env=test --no-interaction
        - composer update
    script:
        - php bin/phpunit
    allow_failure: false
